
Forbidden (Permission denied): /user_delete/django
Traceback (most recent call last):
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 134, in dispatch
    return self.handle_no_permission()
  File "/home/wz/anaconda3/envs/coadd_env/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 48, in handle_no_permission
    raise PermissionDenied(self.get_permission_denied_message())
django.core.exceptions.PermissionDenied
"POST /user_delete/django HTTP/1.1" 403 135
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11284
Forbidden (CSRF token from POST incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2518
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11284
Forbidden (CSRF token from POST incorrect.): /accounts/login/
"POST /accounts/login/ HTTP/1.1" 403 2518
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11284
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 11284
